### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/yacy_ynh#7]
- Hardware: *VPS bought online *
- YunoHost version: 4.3.6.2
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

After I have added multiple URLs into the crawler I get that Nginx error when adding new ones. They do seem to work if I refresh teh page but I am wondering if I should increase the values in the Nginx file:

```
#sub_path_only rewrite ^/$ / permanent;
location / {
  proxy_pass http://127.0.0.1:8090/;
  proxy_redirect off;
  proxy_set_header   Host             $host;
  proxy_set_header   X-Real-IP        $remote_addr;
  proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
  client_max_body_size       10m;
  client_body_buffer_size    128k;
  proxy_connect_timeout      3s;
  proxy_send_timeout         10s;
  proxy_read_timeout         10s;
  proxy_buffer_size          4k;
  proxy_buffers              4 32k;
  proxy_busy_buffers_size    64k;
  proxy_temp_file_write_size 64k;

  # Include SSOWAT user panel.
  #include conf.d/yunohost_panel.conf.inc;
}

location \.(jpg|png|gif|jpeg|css)$ {
  proxy_buffering on;
  proxy_cache_valid 200 120m;
  expires 864000;
}

```

**Comment by yalh76** [comment]
what value do you want to increase ?

**Comment by tio-trom** [comment]
I had since gave up Yacy since it requires a lot of hardware power. I should have closed this issue. I will close it now.
