### ISSUE TITLE
Port 8090 open but Yacy thinks is closed

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/yacy_ynh#8]
- Hardware: *VPS bought online *
- YunoHost version: 4.3.6.2 
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

I have opened the port via the firewall. Restarted it. Even restarted the server. Yacy fails to see it open:
![2022-03-27_22-07](https://user-images.githubusercontent.com/38043315/160298841-1360faca-fd14-443b-b959-56ee84d47a7c.png)

**Comment by MadMan247** [comment]
Why was this closed 😢 

What was the solution?

Edit: You need to manually open the port in yunohost's firewall config. Default 8090.
